### ISSUE TITLE
Interface 'SessionHandlerInterface' not found ?

### ISSUE THREAD

**Issue by fugitive90** [dcro/php-secure-client-side-sessions#1]
Hi,

I am getting this error with PHP5.3 : 

Fatal error: Interface 'SessionHandlerInterface' not found in /www/MasterApp/class/SecureClientSideSessionHandler.php on line 48

Is there any solution to fix this ?

Please help.
Thank you.

**Comment by dcro** [comment]
Sorry but unfortunately [SessionHandlerInterface](http://php.net/manual/ro/class.sessionhandlerinterface.php) and the [session_set_save_handler](http://php.net/manual/ro/function.session-set-save-handler.php) function that accepts a `SessionHandlerInterface` object were only introduced in PHP 5.4.0. 

You could try to make this compatible with PHP 5.3 by adding the interface definition to your app (copy it from the PHP docs linked above) and by changing my code to use the older style `session_set_save_handler` function:

``` php
bool session_set_save_handler(
    callable $open , 
    callable $close, 
    callable $read, 
    callable $write, 
    callable $destroy, 
    callable $gc 
    [ , callable $create_sid ]
)
```

but the better alternative would probably be to upgrade PHP to 5.4.0 or newer.
